all:
  hosts:
    node1:
      ip: 192.168.0.62
      ansible_host: 8.208.12.165
    node2:
      ip: 192.168.0.60
      ansible_host: 8.208.14.1
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
