all:
  hosts:
    node1:
      ip: 192.168.0.177
      ansible_host: 8.208.90.128
    node2:
      ip: 192.168.0.178
      ansible_host: 8.208.112.67
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
