---

- name: Update yum and install docker
  yum: update_cache=yes name=docker state=latest

- name: Install required system packages
  yum: name={{ item }} state=latest update_cache=yes
  loop: [ 'ca-certificates', 'curl' ]

- name: Install pip
  yum:
    name: python-pip
    update_cache: yes
    state: present

- name: Install python-docker
  yum:
    name: python-docker
    update_cache: yes
    state: present

- name: Install Docker SDK for Python
  pip:
    name: "docker<5" 
  become: yes

- name: Add Docker CE repo
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum: name=docker state=latest

- name: Start and enable the Docker daemon
  service: name=docker state=started enabled=yes

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
